# Generated by Django 5.0.6 on 2024-06-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(default='Unknown', max_length=255),
        ),
    ]
